name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      KIVY_WINDOW: mock
      KIVY_GL_BACKEND: mock
      KIVY_NO_ARGS: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml', '**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"

      - name: Run pre-commit (code style & security)
        run: |
          pre-commit run --all-files --show-diff-on-failure

      - name: Run pytest
        run: |
          pytest -q --cov=src/minihometerm --cov-report=term-missing

      - name: Build wheel
        run: |
          python -m build || python -m pip install build && python -m build
